name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Initialize Android Platform
        run: |
          npx cap add android
          npx cap sync android

      - name: Grant Android File Permissions
        run: |
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\n    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />\n    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />' android/app/src/main/AndroidManifest.xml

      - name: Build APK
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: MxGodUI-App.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
